# .super-linter.yml
excludes:
  - "build/**"
  - ".vercel/**"
  - ".next/**"
  - "coverage/**"
  - ".prisma/**"
  - "backend/prisma/migrations/**"
  - "frontend/src/vite-env.d.ts"
  - "frontend/vite.config.ts"
  - "frontend/tsconfig.app.json"
