name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: ja3far
          POSTGRES_PASSWORD: yyeB6wnR
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Use Node.js 18 (or your preferred version)

      # Install dependencies for the entire project (frontend and backend)
      - name: Install dependencies
        run: npm install

      # Set up Prisma
      - name: Install Prisma CLI
        run: npm install -g prisma

      - name: Generate Prisma Client
        working-directory: ./backend
        run: npx prisma generate

      - name: Run database migrations
        working-directory: ./backend
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # Run Super-Linter using .ecrc for exclusions
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LINTER_RULES_PATH: .github/linters  # Optional: Custom linting rules
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          FILTER_REGEX_EXCLUDE: (node_modules/|dist/|build/|\.vercel/|\.next/|coverage/|\.prisma/|backend/prisma/migrations/|frontend/src/vite-env\.d\.ts|frontend/vite\.config\.ts|frontend/tsconfig\.app\.json)

      # - name: Test backend
      #   working-directory: ./backend
      #   run: npm test  # Add a test script in your backend package.json
      #   env:
      #     DATABASE_URL: ${{ secrets.DATABASE_URL }}

      # - name: Test frontend
      #   working-directory: ./frontend
      #   run: npm test  # Add a test script in your frontend package.json

  build:
    runs-on: ubuntu-latest
    needs: lint-and-test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies for the entire project (frontend and backend)
      - name: Install dependencies
        run: npm install

      # Build frontend
      - name: Build frontend
        working-directory: ./frontend
        run: npm run build

      # Build backend (if needed)
      - name: Build backend
        working-directory: ./backend
        run: npm run build

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies for the entire project (frontend and backend)
      - name: Install dependencies
        run: npm install

      # Deploy to Vercel
      - name: Install Vercel CLI
        run: npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}  # Add your Vercel token to GitHub Secrets
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}  # Add your Vercel org ID to GitHub Secrets
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}  # Add your Vercel project ID to GitHub Secrets
        run: |
          vercel --prod --token="$VERCEL_TOKEN"